stages:
  - lint
  - package

shellcheck:
  stage: lint
  image: koalaman/shellcheck-alpine:latest
  script:
    - shellcheck -s bash *.sh
  tags:
    - docker

deb_package:
  stage: package
  image: eugenmayer/make
  script:
    - make
  artifacts:
    paths:
    - bin/*.deb
    expire_in: 6 months
  tags:
    - docker
